# Generated by Django 5.0 on 2025-11-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_active_lesson_indentation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='indentation',
            field=models.IntegerField(default=0),
        ),
    ]
